import { decodeAddress, fromBase64Url, toBase64URL } from './encoding.js';

/**
 * This interface represents the encoded authenticator attestation response
 * typically used in WebAuthn during a registration ceremony. It contains
 * properties that capture the client and attestation data returned by
 * the authenticator, along with optional user and signature information.
 *
 * Properties:
 * - clientDataJSON: A string containing the JSON serialized client data collected during the operation.
 * - attestationObject: A string containing the base64url encoded attestation object generated by the authenticator.
 * - signature: An optional string representing the signature generated by the authenticator for this response.
 * - userHandle: An optional string containing the user handle associated with the credentials being registered.
 * - [k: string]: A utility to define additional optional properties as a key-value pair where the key is a string, and the value is either a string or undefined.
 *
 * @protected
 */
export interface EncodedAuthenticatorAttestationResponse {
  [k: string]: string | undefined;

  /**
   * A string representing the JSON-encoded client data associated with a web authentication operation.
   * This property typically contains information about the client, such as the type of operation
   * (e.g., "webauthn.create" or "webauthn.get"), challenge data, and other contextual metadata.
   * It is used as part of the Web Authentication API for validation and security purposes.
   */
  clientDataJSON: string;
  /**
   * Represents the attestation object used in Web Authentication (WebAuthn) operations.
   * The attestation object is a base64url-encoded string containing authentication metadata.
   * It is generated during the creation of a WebAuthn credential and used to verify
   * the authenticity and origin of the credential.
   *
   * Typically, the attestation object includes details such as:
   * - Information about the authenticator device.
   * - Relevant cryptographic signatures.
   * - Attestation format identifier and other metadata.
   *
   * This string is crucial for validating the generated credential's trustworthiness
   * and ensuring secure communication between the relying party and the authenticator.
   */
  attestationObject: string;
  /**
   * An optional string property that may contain a signature.
   */
  signature?: string;
  /**
   * Represents the unique identifier or handle of a user.
   * This is typically used to reference or display a user's identity
   * within a system where handles or usernames are required.
   * This property is optional and may not always be provided.
   */
  userHandle?: string;
}

/**
 * EncodedAttestationCredential represents an interface for a credential object
 * used in attestation within a Web Authentication API process. It includes
 * essential properties and can also have additional key-value pairs.
 *
 * Properties:
 * - `id`: A string representing the identifier of the credential.
 * - `type`: A string indicating the type of the credential, typically "public-key".
 * - `response`: An object of EncodedAuthenticatorAttestationResponse type which
 *   contains encoded attestation response data.
 * - `rawId`: A string containing the base64url-encoded representation of the
 *   credential's raw identifier.
 * - `[k: string]`: Allows for additional properties, which can be strings or of
 *   the EncodedAuthenticatorAttestationResponse type.
 *
 * @protected
 */
export interface EncodedAttestationCredential {
  [k: string]: string | EncodedAuthenticatorAttestationResponse;

  /**
   * Represents a unique identifier as a string.
   * This identifier is typically used to denote a single distinct entity
   * within a given system or context.
   */
  id: string;
  /**
   * Represents a variable of string type.
   * Used to store textual data.
   */
  type: string;
  /**
   * Represents the attestation response from a WebAuthn authenticator after a
   * registration ceremony using the PublicKeyCredential.create() method.
   * The `response` contains the encoded information necessary to validate
   * and finalize the registration of the credential.
   */
  response: EncodedAuthenticatorAttestationResponse;
  /**
   * Represents the unique identifier in its raw format.
   * Commonly used for internal processing or as a reference to entities in systems.
   * This value should be treated as opaque and not human-readable.
   */
  rawId: string;
}

/**
 * Encodes the given attestation credential into a structured format.
 *
 * @param {PublicKeyCredential} credential - The credential object to be encoded,
 * typically obtained during the registration phase of WebAuthn.
 * @return An object containing the encoded credential information,
 * including its ID, type, and response fields in base64 URL format.
 */
export function encodeCredential(
  credential: PublicKeyCredential,
): EncodedAttestationCredential {
  const response = credential.response as AuthenticatorAttestationResponse;
  return {
    id: credential.id,
    rawId: toBase64URL(credential.rawId),
    type: credential.type,
    response: {
      clientDataJSON: toBase64URL(response.clientDataJSON),
      attestationObject: toBase64URL(response.attestationObject),
    },
  };
}

/**
 * Decodes and processes the attestation options with additional address and challenge decoding.
 *
 * @param {Object} options - The original attestation options, including user and credentials information.
 * @param {Object} liquidOptions - Contains additional data such as the address used for decoding.
 * @return Returns the updated attestation options with decoded user address, display name, and challenge.
 */
export function decodeOptions(options: any, liquidOptions: any) {
  const attestationOptions = { ...options };
  attestationOptions.user.id = decodeAddress(liquidOptions.address);
  attestationOptions.user.name = liquidOptions.address;
  attestationOptions.user.displayName = liquidOptions.address;
  attestationOptions.challenge = fromBase64Url(options.challenge);

  if (attestationOptions.excludeCredentials) {
    for (const cred of attestationOptions.excludeCredentials) {
      cred.id = fromBase64Url(cred.id);
    }
  }

  return attestationOptions;
}
